apiVersion: apps/v1
kind: Deployment
metadata:
  name: guest-app-deployment
  labels:
    app: guest-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: guest-app-pod
      app: guest-app
  template:
     metadata:
       name: guest-app-pod
       labels:
         name: guest-app-pod
         app: guest-app
     spec:
       containers:
         - name:  guest-app
           image: gcr.io/google-samples/gb-frontend:v4
           ports:
             - containerPort: 80
